theking2/kingsoft-persist-db

- composer.json
- src/discover/index.php
> use latest 2.6.1 kingsoft\utils

- src/discover/index.php
> Fix Require session.inc.php from Utils   #9

- index.php
> Move discovered to root

- src/DBPersistTrait.php
> Test if field exists in __set  (prettyprint)

- discover.php
> add additional db types for php string

- composer.json
- src/DBPersistTrait.php
> PK can be anything not just ints

- discover.php
> discover add isPrimaryKeyAutoIncrement

- discover.php
Fixes #38 move to function so params are reinitialized, not generating required methods causes a compile error, which is good
> discover to issue a warning

- README.md
- discover.php
Fixes #45
Update discover.php
and README.md
> Kingma-sbw/issue45

- README.md
- discover.php
Fixes #48
bin2hex(random_bytes(12))
> Don-t use uniqid for keys

- discover.php
> Add support for mediumint

- discover.php
> Handle SET types

- doc.php
> in doc.php only include allowed endpoints

- doc-footer.html
- doc.php
> doc: make update text clearer

- doc-footer.html
- doc.php
> Fix doc.php

- config_sample.php
- discover.php
- doc.php
> Update discover.php to be less dependent on SETTINGS or LOG

- src/Bootstrap.php
> bug missing make final

- src/Bootstrap.php
> make generated classes psr-2 complient

- src/DBPersistTrait.php
> Handles all null values (bind with PARAM_NULL)

- src/DBPersistTrait.php
Fixes #88 convert from strings and Immutables.
> for Date and DateTime fields accept \Date, \DateTime or strings.

- src/DBPersistTrait.php
> Fix consider timezones #92
